### ISSUE TITLE
Percentage not showing for roller blind

### ISSUE THREAD

**Issue by mcolyer** [LennP/PyPi-MotionBlinds_BLE#1]
First off this is fantastic! I was in the middle of reverse engineering this to do exactly what you did - so much better to just have it done.

I just upgraded to HomeAssistant 2024.04 but I don't seem to get any percentages back within the UI of how far down the blind is, is that expected?

**Comment by LennP** [comment]
Hi!

Awesome! Firstly, Motionblinds Bluetooth motors work only using connections which means Home Assistant must first connect after which it receives a status update that includes information on position, tilt, battery percentage, etc. After the motor is disconnected, the cover in Home Assistant will go back saying the position is unknown.

If you use `device.connect()` or the connect button in Home Assistant you should receive position information with the position of the cover being adjusted. On the other hand, if you use the slider then I have configured it to not use the position information. The reason for this is that updating the position of the blind to be open when the user has for example moved the slider to close the blind will result in the cover slider moving down due to the position information when the user has just moved it up to open the blind.

You could of course always keep a permanent connection to the blind by constantly calling the connect service (or this could be an additional feature in the future), but this would only really be useful for blinds that are wired or if you want to always charge the blind, otherwise the battery will of course drain very fast.

> I just upgraded to HomeAssistant 2024.04 but I don't seem to get any percentages back within the UI of how far down the blind is, is that expected?

Unless you use the connect button, you should get percentages back in the UI as mentioned above, even when you are for example connected to the blind and you pull on the cord. If that is not the case or you find something else that does not work, let me know here by leaving a debug log and I will have a look!

**Comment by mcolyer** [comment]
Ah, that's makes sense - I didn't realize you had to connect and disconnect. It seems to be working as expected then.

**Comment by LennP** [comment]
Good to know! This integration works in the same way the Motionblinds Bluetooth mobile app does, which also requires a connection.

There is still an open PR that will add sensors such as a connection sensor that shows whether Home Assistant is connecting, connected, disconnecting, or disconnected to the motor.
